Fixes for Unicode support on Windows.
FreeGLUTProject/freeglut pull request #138
Opened 2023-03-22 00:15 UTC by tweenk

These changes should fix compiling freeglut with -DUNICODE -D_UNICODE on Windows.

2023-03-23 01:45 UTC, jtsiomb requested changes
I'm not usually involved with the windows side of things, so I'll wait a while for anyone else to respond. I only have a couple of general comments for now.

2023-03-23 01:45 UTC, jtsiomb commented on src/mswin/fg_window_mswin.c
> +    TCHAR* tstr = fghTstrFromStr(title);
For maximum compatibility, freeglut is written in C89. You can't define variables everywhere in the code, only at the top of a scope. Please move the delcaration of tstr to the start of the function.

2023-03-23 01:45 UTC, jtsiomb commented on src/mswin/fg_joystick_mswin.c
> +    dwcb = _countof(OEMKey);
_countof does not exist on MSVC 6. From the docs it looks like it's simply a macro expanding to `sizeof foo / sizeof *foo`, so please use that instead.

2023-03-23 01:45 UTC, jtsiomb commented on src/mswin/fg_joystick_mswin.c
> +    _snprintf ( buffer, _countof(buffer), _T("%s\\%s"), REGSTR_PATH_JOYOEM, OEMKey );
shouldn't this also be `_sntprintf`?

2023-03-29 04:21 UTC, tweenk commented on src/mswin/fg_joystick_mswin.c
> +    _snprintf ( buffer, _countof(buffer), _T("%s\\%s"), REGSTR_PATH_JOYOEM, OEMKey );
Yes, fixed.

2023-03-29 04:23 UTC, tweenk commented
Uploaded new version with the requested changes

2023-03-29 19:31 UTC, dcnieho commented
yes, i can test once its ready

> Message ID: ***@***.***>
>

2023-03-30 05:48 UTC, tweenk commented
It looks like I made a typo when 'exporting' the change. For context, I do not have access to a Windows machine at the moment. I made these changes to a copy of the library in the Google internal monorepo, then compiled an internal demo application that uses freeglut using a cross-compilation toolchain and ran it in Wine. I then manually applied the same changes to a GitHub checkout and uploaded it, but I made a mistake during this process.

To ensure I didn't make this type of mistake this time, I used the automatic source copying tool [Copybara](https://github.com/google/copybara).

2023-03-30 06:19 UTC, dcnieho commented
Thanks! So this should be ready to test?

> Message ID: ***@***.***>
>

2023-03-30 18:22 UTC, tweenk commented
Yes, it should be ready to test now.

2023-04-02 14:05 UTC, dcnieho commented
Tested, compiles and the demo apps work fine

2023-04-02 19:14 UTC, merged